# Generated by Django 4.0.5 on 2022-07-29 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Florence', '0014_order_shippingadress_orderitem'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='new',
        ),
    ]
