# Generated by Django 4.0.5 on 2022-07-29 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Florence', '0017_alter_category_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
    ]
